MAIN=server.js
MEMORY=512
VERSION=recommended
DISPLAY_NAME=ZER01 Roleplay
DESCRIPTION=Portal oficial ZER01 Roleplay com editor visual
SUBDOMAIN=zer01roleplay
START=npm start
AUTORESTART=true
RUNTIME=nodejs
